services:
  #our application
  BlackFridayLoadTester:
    build:
      dockerfile: BlackFriday.LoadTester/Dockerfile
      context: .
    hostname: black-friday-load-tester
    image: black-friday-load-tester
    environment:
      - LOADTESTER_BLACKFRIDAY_SERVER_URI=http://host.docker.internal:32768
      - LOADTESTER_USERSCOUNT=5
