// <auto-generated />
using System;
using FoodReservation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodReservation.Infrastructure.Persistence.DbMigrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240712083209_UpdateDailyFoodsTableName")]
    partial class UpdateDailyFoodsTableName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodReservation.Domain.Entities.FoodReservation", b =>
                {
                    b.Property<Guid>("FoodId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FoodId", "UserId", "Date");

                    b.HasIndex("FoodId", "Date");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("FoodReservation.Domain.Entities.ReservableDailyFood", b =>
                {
                    b.Property<Guid>("FoodId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.HasKey("FoodId", "Date");

                    b.ToTable("DailyFoods");
                });

            modelBuilder.Entity("FoodReservation.Domain.Entities.ReservableFood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("FoodReservation.Domain.Entities.FoodReservation", b =>
                {
                    b.HasOne("FoodReservation.Domain.Entities.ReservableFood", null)
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodReservation.Domain.Entities.ReservableDailyFood", null)
                        .WithMany()
                        .HasForeignKey("FoodId", "Date")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodReservation.Domain.Entities.ReservableDailyFood", b =>
                {
                    b.HasOne("FoodReservation.Domain.Entities.ReservableFood", null)
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
